In [1]:
import pandas as pd

alunos = {'Nome':['Paulo','Roberto','Ricardo','Saulo'],'Nota':[4,5.5,7,9],'Aprovado':['Não','Não','Sim','Sim']}

dataframe = pd.DataFrame(alunos)

In [2]:
print(dataframe)

      Nome  Nota Aprovado
0    Paulo   4.0      Não
1  Roberto   5.5      Não
2  Ricardo   7.0      Sim
3    Saulo   9.0      Sim


In [3]:
objeto1 = pd.Series([1, 2, 3, 4])
print(objeto1)

0    1
1    2
2    3
3    4
dtype: int64


In [4]:
import numpy as np
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [5]:
array2 = np.array([(1,2,3,4),(5,6,7,8)])
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
objeto2 = pd.Series(array)
print(objeto2)

0    1
1    2
2    3
3    4
dtype: int64
