In [4]:
import numpy as np
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [5]:
b = np.array([(1,2,3),(8,2,9),(1,7,5)])
print(b)

[[1 2 3]
 [8 2 9]
 [1 7 5]]


In [6]:
c = np.zeros((4,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Mostra o maior numero

In [10]:
b.max()

9

Mostra o menor numero

In [15]:
b.min()

1

Mostra a soma dos numeros

In [16]:
b.sum()

38

Mostra a média dos números

In [13]:
b.mean()

4.222222222222222

Mostra desvio padrão dos números

In [14]:
b.std()

2.9355210696939795